db_file: "bot.db"

apihost: "https://api.kinopoisk.dev/v1.4"
endpoint_movie_search: "/movie/search"

messages:
  responses:
    start: "Привет! Я бот для поиска и сохранения фильмов \"Kinopoisk Search Bot\" 🎥\n\n"
    help: "Просто отправь мне название фильма, который ты хочешь ты хочешь найти, и я постараюсь помочь тебе. После того как я найду фильм, ты сможешь сохранить его в свой список любимых фильмов. Начни с написания названия фильма! 📥"
    unknown_command: "Я не знаю такой команды 😢"
    is_the_movie: "Это тот фильм, который вы искали?"
    add_successfully: "Фильм успешно добавлен в список! 🥳"
    your_movies: "Ваш список фильмов:"
    push_the_button: "Нужно нажать на кнопку 😕"
  errors:
    default: "Произошла неизвестная ошибка 😔"
    fav_list_is_empty: "Твой список фильмов пока что пуст. Для начала отправь мне название фильма, который хочешь добавить! 📥"
    cant_fetch_movies: "Не получилось найти фильм. Попробуй ввести название еще раз 😔"
    rec_exists: "Этот фильм уже есть в твоем списке 😇"
    cant_insert: "Не получилось сохранить фильм. Попробуй еще раз 😔"
    end_of_search: "Вы просмотрели все найденные фильмы. Пожалуйста, перепроверьте название фильма 😕"

