name: CI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "miittya/kinopoisk-telegram-bot"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t $IMAGE_NAME:$GITHUB_SHA .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: docker push $IMAGE_NAME:$GITHUB_SHA

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to VPS Beget via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.BEGET_HOST }}
          username: ${{ secrets.BEGET_USERNAME }}
          key: ${{ secrets.BEGET_SSH_KEY }}
          script: |
            # Pull the latest image from Docker Hub
            docker pull $IMAGE_NAME:$GITHUB_SHA

            # Stop running container (if exists)
            docker stop kinopoisk-telegram-bot || true
            docker rm kinopoisk-telegram-bot || true

            # Run a new container with the updated image
            docker run -d -p 8080:8080 \
            -e TG_API_KEY=7102497643:AAHhU0QWMCeqfCg6aIzamZLv_M5tgUxk0is -e X-API-KEY=C3HKNMR-SM24AA1-GRQSKP0-NV7Q67N \
            --name kinopoisk-telegram-bot \
            $IMAGE_NAME:$GITHUB_SHA
