name: CI

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t miittya/kinopoisk-telegram-bot .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: docker push miittya/kinopoisk-telegram-bot

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to VPS Beget via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.BEGET_HOST }}
          username: ${{ secrets.BEGET_USERNAME }}
          key: ${{ secrets.BEGET_SSH_KEY }}
          script: |
            # Pull the latest image from Docker Hub
            docker pull miittya/kinopoisk-telegram-bot


            # Stop running container (if exists)
            docker stop telegram-bot
            docker rm telegram-bot

            # Run a new container with the updated image
            docker run -d -p 8080:8080 \
            -e TG_API_KEY=7102497643:AAHhU0QWMCeqfCg6aIzamZLv_M5tgUxk0is -e X-API-KEY=C3HKNMR-SM24AA1-GRQSKP0-NV7Q67N \
            --name telegram-bot \
            miittya/kinopoisk-telegram-bot
